name: Publish Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            DOCKER_PASSWORD: dockerhub-password
            DOCKER_USERNAME: dockerhub-username

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push mockserver-init
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mockserver/init/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: extenda/hiiretail-devkit-mockserver-init:latest

      - name: Build and push webhook-playground
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./webhook-playground/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: extenda/hiiretail-devkit-webhook-playground:latest

      - name: Build and push webhook-receiver
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./webhook-receiver/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: extenda/hiiretail-devkit-webhook-receiver:latest
